.TH baka-mplayer 1
.SH NAME
baka-mplayer - A free and open source, cross-platform, \fBlibmpv\fP based multimedia player.

.SH SYNOPSIS
\fBbaka-mplayer\fP [file|-]

.SH DESCRIPTION
\fBBaka-MPlayer\fP is a free and open source, cross-platform, \fBlibmpv\fP based multimedia player. Its simple design reflects the idea for an uncluttered, simple, and enjoyable environment for watching tv shows.
.PP
\fBBaka-MPlayer\fP is a graphical front-end to \fBmpv\fP. It is mostly self-explanatory and has little need for a manual.

.SH EXAMPLES
.nf
\fBbaka-mplayer\fP
\fBbaka-mplayer\fP myvideo.mkv
cat myvideo.mkv | \fBbaka-mplayer\fP -

.SH SEE ALSO
\fBmpv\fP

.SH BUGS
Please use the issues tracker provided by GitHub to send us bug reports or feature requests. (https://github.com/u8sand/Baka-MPlayer/issues)

.SH AUTHORS
\fBBaka-MPlayer\fP was written by \fBu8sand\fP <u8sand@gmail.com> and \fBgodly-devotion\fP <azian.otaku@live.com>.

.SH COPYRIGHT
GPLv2+
