name: Deploy website to gh-pages
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install & build
      run: |
        cd website
        gem install bundler -v 2.4.22
        bundle install
        bundle exec jekyll build
        cd ..

    - uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: website/_site
        BRANCH: gh-pages
        CLEAN: true
