name: Deploy website to gh-pages
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'website/**'
permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v7

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install & build
      run: |
        cd website
        gem install bundler
        bundle install
        bundle exec jekyll build
        cd ..

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: website/_site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
